name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TEST_SOLUTION_FILE: LostHarbor.Tests.sln

jobs:
  test:
    name: Execute Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore ${{ env.TEST_SOLUTION_FILE }}

    - name: Run tests
      run: dotnet test --no-restore --logger:"console;verbosity=normal" --nologo ${{ env.TEST_SOLUTION_FILE }}
